import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const responseObj = api.openai.prompt.useQuery({ prompt: 'What is the meaning of life?' });
  const responseObj = api.openai.prompt.useQuery({ prompt: 'Como funciona o sistema nervoso?' });

  const user = useUser()

  console.log(responseObj?.data?.response)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Cursed <span className="text-[hsl(280,100%,70%)]">BDAY</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-1 md:gap-8">
            {!user.isSignedIn && <SignInButton />}
            {!!user.isSignedIn && <SignOutButton />}
          </div>
          <p className="text-2xl text-white">
            {responseObj.data ? responseObj.data.response : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
